# Generated by Django 3.2.12 on 2022-04-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intoli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='browser',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='os',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
