# Generated by Django 3.2.12 on 2022-04-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intoli', '0002_auto_20220402_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='browser',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='device_category',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='os',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='platform',
            field=models.CharField(max_length=32),
        ),
    ]
