# Generated by Django 3.2.12 on 2022-04-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intoli', '0003_auto_20220402_0125'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='device_category_index',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='platform_index',
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['browser'], name='profile_browser'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['device_category'], name='profile_device_category'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['os'], name='profile_os'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['platform'], name='profile_platform'),
        ),
    ]
