# Generated by Django 3.2.12 on 2022-02-20 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('device_category', models.CharField(max_length=16)),
                ('platform', models.CharField(max_length=16)),
                ('screen_height', models.IntegerField()),
                ('screen_width', models.IntegerField()),
                ('user_agent', models.TextField()),
                ('viewport_height', models.IntegerField()),
                ('viewport_width', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=24, max_digits=25)),
            ],
            options={
                'db_table': 'intoli_profile',
                'ordering': ['-weight'],
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['device_category'], name='device_category_index'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['platform'], name='platform_index'),
        ),
    ]
