# Generated by Django 3.2.13 on 2022-04-30 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djspoofer', '0023_auto_20220428_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='H2FrameFingerprint',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('header_table_size', models.IntegerField()),
                ('enable_push', models.BooleanField(blank=True, null=True)),
                ('max_concurrent_streams', models.IntegerField(blank=True, null=True)),
                ('initial_window_size', models.IntegerField()),
                ('max_frame_size', models.IntegerField(blank=True, null=True)),
                ('max_header_list_size', models.IntegerField(blank=True, null=True)),
                ('psuedo_header_order', models.TextField()),
            ],
            options={
                'db_table': 'djspoofer_h2_frame_fingerprint',
                'ordering': ['-created'],
            },
        ),
    ]
