# Generated by Django 3.2.13 on 2022-05-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djspoofer', '0024_h2framefingerprint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='H2FrameFingerprint',
            new_name='H2SettingsFingerprint',
        ),
        migrations.AlterModelTable(
            name='h2settingsfingerprint',
            table='djspoofer_h2_settings_fingerprint',
        ),
    ]
