# Generated by Django 3.2.13 on 2022-05-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djspoofer', '0025_auto_20220501_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='h2settingsfingerprint',
            name='priority_depends_on_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h2settingsfingerprint',
            name='priority_exclusive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h2settingsfingerprint',
            name='priority_stream_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h2settingsfingerprint',
            name='priority_weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='h2settingsfingerprint',
            name='window_update_increment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
