# Generated by Django 3.2.13 on 2022-05-03 22:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('djspoofer', '0026_auto_20220502_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('browser', models.CharField(max_length=32)),
                ('device_category', models.CharField(max_length=32)),
                ('os', models.CharField(max_length=32)),
                ('platform', models.CharField(max_length=32)),
                ('screen_height', models.IntegerField()),
                ('screen_width', models.IntegerField()),
                ('user_agent', models.TextField()),
                ('viewport_height', models.IntegerField()),
                ('viewport_width', models.IntegerField()),
            ],
            options={
                'db_table': 'djspoofer_device_fingerprint',
            },
        ),
        migrations.CreateModel(
            name='H2Fingerprint',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('browser', models.CharField(max_length=32)),
                ('browser_min_major_version', models.IntegerField(default=0)),
                ('browser_max_major_version', models.IntegerField(default=999)),
                ('os', models.CharField(max_length=32)),
                ('header_table_size', models.IntegerField()),
                ('enable_push', models.BooleanField(blank=True, null=True)),
                ('max_concurrent_streams', models.IntegerField(blank=True, null=True)),
                ('initial_window_size', models.IntegerField()),
                ('max_frame_size', models.IntegerField(blank=True, null=True)),
                ('max_header_list_size', models.IntegerField(blank=True, null=True)),
                ('psuedo_header_order', models.TextField()),
                ('window_update_increment', models.IntegerField()),
                ('priority_stream_id', models.IntegerField()),
                ('priority_exclusive', models.BooleanField()),
                ('priority_depends_on_id', models.IntegerField()),
                ('priority_weight', models.IntegerField()),
            ],
            options={
                'db_table': 'djspoofer_h2_fingerprint',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('oid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=2)),
                ('isp', models.CharField(max_length=64)),
                ('address', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'djspoofer_ip',
                'ordering': ['-created'],
            },
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='IntoliFingerprint',
        ),
        migrations.DeleteModel(
            name='H2SettingsFingerprint',
        ),
        migrations.RemoveIndex(
            model_name='fingerprint',
            name='fp_browser',
        ),
        migrations.RemoveIndex(
            model_name='fingerprint',
            name='fp_device_category',
        ),
        migrations.RemoveIndex(
            model_name='fingerprint',
            name='fp_platform',
        ),
        migrations.RemoveIndex(
            model_name='intolifingerprint',
            name='iprofile_browser',
        ),
        migrations.RemoveIndex(
            model_name='intolifingerprint',
            name='iprofile_device_category',
        ),
        migrations.RemoveIndex(
            model_name='intolifingerprint',
            name='iprofile_os',
        ),
        migrations.RemoveIndex(
            model_name='intolifingerprint',
            name='iprofile_platform',
        ),
        migrations.RemoveField(
            model_name='fingerprint',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='fingerprint',
            name='device_category',
        ),
        migrations.RemoveField(
            model_name='fingerprint',
            name='ip_fingerprints',
        ),
        migrations.RemoveField(
            model_name='fingerprint',
            name='os',
        ),
        migrations.RemoveField(
            model_name='fingerprint',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='fingerprint',
            name='screen_height',
        ),
        migrations.RemoveField(
            model_name='fingerprint',
            name='screen_width',
        ),
        migrations.RemoveField(
            model_name='fingerprint',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='fingerprint',
            name='viewport_height',
        ),
        migrations.RemoveField(
            model_name='fingerprint',
            name='viewport_width',
        ),
        migrations.AddField(
            model_name='tlsfingerprint',
            name='browser_max_major_version',
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name='tlsfingerprint',
            name='browser_min_major_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tlsfingerprint',
            name='os',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='intolifingerprint',
            index=models.Index(fields=['browser'], name='idx_intoli_fp_browser'),
        ),
        migrations.AddIndex(
            model_name='intolifingerprint',
            index=models.Index(fields=['device_category'], name='idx_intoli_fp_device_category'),
        ),
        migrations.AddIndex(
            model_name='intolifingerprint',
            index=models.Index(fields=['os'], name='idx_intoli_fp_os'),
        ),
        migrations.AddIndex(
            model_name='intolifingerprint',
            index=models.Index(fields=['platform'], name='idx_intoli_fp_platform'),
        ),
        migrations.AlterModelTable(
            name='intolifingerprint',
            table='djspoofer_intoli_fingerprint',
        ),
        migrations.DeleteModel(
            name='IPFingerprint',
        ),
        migrations.AddIndex(
            model_name='ip',
            index=models.Index(fields=['city'], name='ip_fp_city'),
        ),
        migrations.AddIndex(
            model_name='ip',
            index=models.Index(fields=['country'], name='ip_fp_country'),
        ),
        migrations.AddIndex(
            model_name='ip',
            index=models.Index(fields=['isp'], name='ip_fp_isp'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['browser'], name='idx_device_fp_browser'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['device_category'], name='idx_device_fp_device_category'),
        ),
        migrations.AddIndex(
            model_name='devicefingerprint',
            index=models.Index(fields=['platform'], name='idx_device_fp_platform'),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='device_fingerprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='djspoofer.devicefingerprint'),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='ip',
            field=models.ManyToManyField(to='djspoofer.IP'),
        ),
    ]
