# Generated by Django 3.2.13 on 2022-05-04 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djspoofer', '0027_auto_20220503_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicefingerprint',
            name='browser_major_version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='h2_fingerprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='djspoofer.h2fingerprint'),
        ),
        migrations.AddField(
            model_name='intolifingerprint',
            name='browser_major_version',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
